### ISSUE TITLE
Object decoded from query unable to resave into database

### ISSUE THREAD

**Issue by Ave700** [couchbaselabs/couchbase-lite-swift-coder#1]
I've run into an issue where if I query the database and decode the results my objects have all their data and behave as expected. If I then change a variable and try object.save(into: db) it fails. If instead I get the object with the db.document(withID: as: object.self) method the object can be saved no issues. Maybe this is expected? Or is it expected to be able to modify objects collected from queries?

**Comment by pasin** [comment]
Document itself is readonly so you would need to get the MutableDocument by calling toMutable() and then decode the MutableDocument.

**Comment by pasin** [comment]
Sorry for replying this late. For some reason, I didn't get notification at all.
